comment on table families is 'Семьи, для которых сервер хранит настройки и рассчитывает агрегаты.';
comment on column families.id is 'Уникальный идентификатор семьи.';
comment on column families.name is 'Название семьи.';
comment on column families.timezone is 'Таймзона семьи, используемая в расчетах и отображении времени.';
comment on column families.currency_code is 'Код валюты, в которой отображаются показатели семьи.';
comment on column families.status is 'Текущий статус семьи в справочной модели.';
comment on column families.created_at is 'Момент создания записи о семье.';
comment on column families.updated_at is 'Момент последнего изменения записи о семье.';

comment on table family_members is 'Члены семьи, для которых сервер собирает и хранит финансовые данные.';
comment on column family_members.id is 'Уникальный идентификатор члена семьи.';
comment on column family_members.family_id is 'Идентификатор семьи, к которой относится пользователь.';
comment on column family_members.first_name is 'Имя пользователя.';
comment on column family_members.last_name is 'Фамилия пользователя.';
comment on column family_members.display_name is 'Короткое отображаемое имя для интерфейсов и интеграций.';
comment on column family_members.telegram_chat_id is 'Telegram chat id для запуска и продолжения диалога.';
comment on column family_members.telegram_username is 'Telegram username пользователя.';
comment on column family_members.is_active is 'Признак участия пользователя в текущем MVP-сценарии.';
comment on column family_members.created_at is 'Момент создания записи о пользователе.';
comment on column family_members.updated_at is 'Момент последнего изменения записи о пользователе.';

comment on table devices is 'Физические устройства, которые получают семейный dashboard.';
comment on column devices.id is 'Уникальный идентификатор устройства.';
comment on column devices.family_id is 'Идентификатор семьи, к которой привязано устройство.';
comment on column devices.name is 'Человекочитаемое имя устройства.';
comment on column devices.device_token_hash is 'Хэш токена устройства для аутентификации запросов.';
comment on column devices.status is 'Текущий статус доступности устройства.';
comment on column devices.last_seen_at is 'Время последнего успешного обращения устройства к серверу.';
comment on column devices.created_at is 'Момент создания записи об устройстве.';
comment on column devices.updated_at is 'Момент последнего изменения записи об устройстве.';

comment on table member_payroll_schedules is 'Правила зарплатных событий для членов семьи.';
comment on column member_payroll_schedules.id is 'Уникальный идентификатор правила выплаты.';
comment on column member_payroll_schedules.member_id is 'Идентификатор пользователя, для которого настроено правило выплаты.';
comment on column member_payroll_schedules.label is 'Краткое название правила выплаты.';
comment on column member_payroll_schedules.schedule_type is 'Тип расчета зарплатной даты.';
comment on column member_payroll_schedules.day_of_month is 'День месяца для фиксированной даты выплаты.';
comment on column member_payroll_schedules.trigger_delay_days is 'Количество дней между выплатой и запуском опроса.';
comment on column member_payroll_schedules.is_active is 'Признак участия правила в автоматическом запуске сбора.';
comment on column member_payroll_schedules.created_at is 'Момент создания правила выплаты.';
comment on column member_payroll_schedules.updated_at is 'Момент последнего изменения правила выплаты.';

comment on table llm_collection_requests is 'Запуски LLM-опросов по конкретным зарплатным событиям.';
comment on column llm_collection_requests.id is 'Уникальный идентификатор запроса на сбор данных.';
comment on column llm_collection_requests.request_id is 'Основной correlation id цепочки server -> n8n -> Telegram -> server.';
comment on column llm_collection_requests.family_id is 'Идентификатор семьи, для которой инициирован сбор данных.';
comment on column llm_collection_requests.member_id is 'Идентификатор пользователя, которого необходимо опросить.';
comment on column llm_collection_requests.payroll_schedule_id is 'Идентификатор правила выплаты, породившего запуск опроса.';
comment on column llm_collection_requests.period_year is 'Год расчетного периода, для которого собираются данные.';
comment on column llm_collection_requests.period_month is 'Месяц расчетного периода, для которого собираются данные.';
comment on column llm_collection_requests.reason is 'Причина запуска опроса.';
comment on column llm_collection_requests.status is 'Текущий статус жизненного цикла интеграционного запроса.';
comment on column llm_collection_requests.requested_fields is 'JSON-массив полей, которые нужно собрать в рамках опроса.';
comment on column llm_collection_requests.nominal_payroll_date is 'Номинальная дата выплаты без учета переносов.';
comment on column llm_collection_requests.effective_payroll_date is 'Фактическая дата выплаты после применения правил переноса.';
comment on column llm_collection_requests.scheduled_trigger_date is 'Дата, в которую сервер должен запустить сбор данных.';
comment on column llm_collection_requests.triggered_at is 'Время отправки запроса в интеграционный контур.';
comment on column llm_collection_requests.accepted_at is 'Время, когда n8n подтвердил прием запроса.';
comment on column llm_collection_requests.completed_at is 'Время успешного завершения всей цепочки сбора данных.';
comment on column llm_collection_requests.workflow_run_id is 'Идентификатор workflow run на стороне n8n.';
comment on column llm_collection_requests.request_payload is 'JSON payload, который сервер отправил в n8n.';
comment on column llm_collection_requests.response_payload is 'JSON payload ответа от n8n при успешном запуске workflow.';
comment on column llm_collection_requests.error_message is 'Текст ошибки интеграции, если запрос завершился неуспешно.';
comment on column llm_collection_requests.created_at is 'Момент создания записи о запросе на сбор данных.';
comment on column llm_collection_requests.updated_at is 'Момент последнего изменения записи о запросе на сбор данных.';

comment on table finance_submissions is 'Результаты intake-опросов с финансовыми данными пользователей.';
comment on column finance_submissions.id is 'Уникальный идентификатор intake submission.';
comment on column finance_submissions.external_submission_id is 'Внешний идентификатор submission со стороны интеграции.';
comment on column finance_submissions.request_id is 'Correlation id исходного запуска опроса.';
comment on column finance_submissions.llm_collection_request_id is 'Идентификатор связанного запроса на сбор данных при наличии request id.';
comment on column finance_submissions.family_id is 'Идентификатор семьи, к которой относятся присланные данные.';
comment on column finance_submissions.member_id is 'Идентификатор пользователя, которого опрашивали.';
comment on column finance_submissions.source is 'Канал, из которого пришли данные.';
comment on column finance_submissions.period_year is 'Год расчетного периода, к которому относится ответ.';
comment on column finance_submissions.period_month is 'Месяц расчетного периода, к которому относится ответ.';
comment on column finance_submissions.collected_at is 'Время завершения опроса и фиксации значений пользователем.';
comment on column finance_submissions.monthly_income is 'Доход по конкретному payroll-событию.';
comment on column finance_submissions.monthly_expenses is 'Актуальная оценка расходов пользователя за месяц.';
comment on column finance_submissions.monthly_credit_payments is 'Актуальная оценка кредитных платежей пользователя за месяц.';
comment on column finance_submissions.liquid_savings is 'Объем доступных накоплений пользователя на момент опроса.';
comment on column finance_submissions.confidence is 'Оценка уверенности в корректности полученных значений.';
comment on column finance_submissions.notes is 'Дополнительное текстовое пояснение к ответу пользователя.';
comment on column finance_submissions.raw_payload is 'Исходный intake payload в нормализованном JSON-формате.';
comment on column finance_submissions.created_at is 'Момент создания записи о submission.';

comment on table member_finance_snapshots is 'Месячные агрегированные снимки финансового состояния членов семьи.';
comment on column member_finance_snapshots.id is 'Уникальный идентификатор месячного снимка пользователя.';
comment on column member_finance_snapshots.family_id is 'Идентификатор семьи, для которой хранится снимок.';
comment on column member_finance_snapshots.member_id is 'Идентификатор пользователя, по которому рассчитан снимок.';
comment on column member_finance_snapshots.period_year is 'Год расчетного периода снимка.';
comment on column member_finance_snapshots.period_month is 'Месяц расчетного периода снимка.';
comment on column member_finance_snapshots.source_submission_id is 'Идентификатор самой свежей submission, определившей неаддитивные поля снимка.';
comment on column member_finance_snapshots.monthly_income is 'Суммарный доход пользователя за месяц.';
comment on column member_finance_snapshots.monthly_expenses is 'Актуальная оценка расходов пользователя за месяц.';
comment on column member_finance_snapshots.monthly_credit_payments is 'Актуальная оценка кредитных платежей пользователя за месяц.';
comment on column member_finance_snapshots.liquid_savings is 'Актуальный объем ликвидных накоплений пользователя.';
comment on column member_finance_snapshots.collected_at is 'Время самой свежей submission, использованной для снимка.';
comment on column member_finance_snapshots.created_at is 'Момент создания месячного снимка пользователя.';
comment on column member_finance_snapshots.updated_at is 'Момент последнего изменения месячного снимка пользователя.';

comment on table family_dashboard_snapshots is 'Готовые семейные dashboard-снимки для физического устройства.';
comment on column family_dashboard_snapshots.id is 'Уникальный идентификатор семейного dashboard-снимка.';
comment on column family_dashboard_snapshots.family_id is 'Идентификатор семьи, для которой рассчитан dashboard.';
comment on column family_dashboard_snapshots.period_year is 'Год расчетного периода dashboard.';
comment on column family_dashboard_snapshots.period_month is 'Месяц расчетного периода dashboard.';
comment on column family_dashboard_snapshots.status is 'Машинное значение итогового статуса семьи.';
comment on column family_dashboard_snapshots.status_text is 'Короткий текст статуса для интерфейса устройства.';
comment on column family_dashboard_snapshots.status_reason is 'Причина выбранного статуса для второй строки экрана.';
comment on column family_dashboard_snapshots.monthly_income is 'Суммарный доход семьи за месяц.';
comment on column family_dashboard_snapshots.monthly_expenses is 'Актуальная оценка месячных расходов семьи.';
comment on column family_dashboard_snapshots.credit_load_percent is 'Кредитная нагрузка семьи в процентах.';
comment on column family_dashboard_snapshots.emergency_fund_months is 'Размер подушки безопасности семьи в месяцах расходов.';
comment on column family_dashboard_snapshots.member_count_used is 'Количество участников семьи, включенных в расчет dashboard.';
comment on column family_dashboard_snapshots.calculated_at is 'Время фактического расчета dashboard.';
comment on column family_dashboard_snapshots.created_at is 'Момент создания семейного dashboard-снимка.';
comment on column family_dashboard_snapshots.updated_at is 'Момент последнего изменения семейного dashboard-снимка.';
